### ISSUE TITLE
Issues with gpgsql

### ISSUE THREAD

**Issue by templatedop** [ClarkQAQ/uw#1]
Hi
I am testing your gpgsql https://github.com/ClarkQAQ/gpgsql

But it is struck at g.start

When I debugged further cmd.Run is waiting endlessly 

Can you please look into it

**Comment by templatedop** [comment]
Since the library is made read only I have to submit issue here

**Comment by ClarkQAQ** [comment]
Thank you! But I'm no longer maintaining it.
